INSERT INTO `critics` (`id`, `user_id`,`film_id`,`comment`) VALUES
(1,1,1,'This movie is hands down amazing.'),
(2,2,1,'he dinosaur runs down the stairs at the school to escape Tommy and Chloe, but it looks more like he floats down instead.'),
(3,1,2,'Me and my friends watched this movie one sleepover.'),
(4,2,2,'This movie seems like a good movie for teenagers to laugh and joke about but it wont appeal to anyone else...maybe kids and dinosaurs'),
(5,1,3,'I don`t know were all the fantastic and amazing CGI reviews are coming from...'),
(6,2,3,'Obviously they`ve never seen Jurassic World or the Avengers movies. This movie was terrible.'),
(7,1,4,'he acting was as if they were in a child`s play, the close up of the dinosaur looks to be a plastic arm puppet.'),
(8,2,4,'it was a great movie at the end i did not suspect it to have a sister and that sister to be a t-rex very good movie'),
(9,1,5,'I havent wach the movie yet but I met one of the actors today and she was nice'),
(10,2,5,'This is the best movie ever the puppet floats down the stairs it`s just a 5star!'),
(11,1,6,'CGI was fantastic'),
(12,2,6,'Waste of time. Extremely poor'),
(13,1,7,'Fun tv , heary warming and works well in region 2 playera'),
(14,2,7,'We have already watched the complete series and it was great. Service was also very good as we received our order in just days.'),
(15,1,8,'No swears or immorality. A true family show with.'),
(16,2,8,'Am pleased with the product and the service.'),
(17,1,9,'I love this series. Leaves you with a good feeling. Family friendly.'),
(18,2,9,'i really enjoyed watching this show alot'),
(19,1,10,'Yes. Have seen the films several times but it is good to see them at home in your own time.'),
(20,2,10,'Had seen both of these before and I still think they are good, first is better though!'),
(21,1,11,'Although people say Halmark movies are repetitive but I find that sometimes you need a movie with a happy ending. Hallmark movies are entertaining and fun so it makes them good in my book'),
(22,2,11,'Totally enjoyed'),
(23,1,12,'This is an other series that I loved. Murder mystery are really great'),
(24,2,12,'Love this series I wish they had more!!!');